edit_btn
Hresko/Ice-Cream pull request #32
Opened 2022-06-25 16:29 UTC by OlenaBut

внесла коррективи
по мобільній версії, начебто, все.
щодо модалки, яку повинні відкривати ці кнопки: багато питаннь, як-от: 
1. контент модалки? якщо по Локації щось можна насмикати з існуючого, то по Франшизі я просто гублюся
2. де те вікно повинно відчинятись?! наприкінці блоку контактів, абошо??

... тому, шановне панство, я теє не стала чіпляти. До того ж, "Оскільки дизайну модального вікна немає, це можна реалізувати додатково."(с) - необов’язковість цього мені подобається))

2022-06-25 21:08 UTC, rudenkoserhii commented on src/partials/contacts.html
> +                        <li class="contact__date__item">
Тут і далі у подібних не потрібно писати date__

2022-06-25 21:18 UTC, OlenaBut commented on src/partials/contacts.html
> +                        <li class="contact__date__item">
аргументуйте, будь ласка
бо, якщо я приберу date_, в мене вже є <ul class="contact list"> та <li class="contact__item"> з прописаними до них стилями, і як бути з цим?

2022-06-25 21:24 UTC, rudenkoserhii commented on src/partials/contacts.html
> +                        <li class="contact__date__item">
Це з конспекту:
ВНИМАНИЕ
Элемент - всегда часть блока, а не другого элемента. Это значит, что в имени класса элемента нельзя прописывать иерархию вида блок__элемент1__элемент2.

І звісно ж стилі потрібно буде підправити

2022-06-26 06:57 UTC, JuliaGolban requested changes
1. ви не оновили main перед тим, як запушили свою гілку - у вас там старі данні (інструкція в слаці, відео подивіться з наших зустрічей брейн-штормів, де ми оговорюємо загальні питання також, що б не витрачати години з кожним окремо, бо нас 9)
2. додайте в section id="contacts"
3. модальних вікон не робите, а ті кольорові то просто span можна
4. contact__text - не треба робити верхній маржин, у вас є нижній у тайтли
5. зробіть нижній 24 і не робіть верхній на афтер (є правило: низ - право)
6. спочатку йде телефон, потім мейл
7. contact__item - на макеті 20 маржин нижній
8. у вас там не сплошна лінія, а якийсь прямокутник, треба просто лінія 1рх
9. скритий заголовок пишіть на англ, тому що мова сторінки - англ

2022-06-26 14:21 UTC, JuliaGolban commented on src/partials/contacts.html
> +        <h2 class="visually-hidden" class="section-title">Наши контакты</h2>
тут разом класи пишуться через пробіл

2022-06-26 14:22 UTC, JuliaGolban commented on src/sass/layouts/_contacts.scss
> +    background: var(--cl-txt-white);
в нас є для bgc var(--bgc-main)

2022-06-26 14:23 UTC, JuliaGolban commented on src/sass/layouts/_contacts.scss
> +    font-family: 'DM Sans';
у нас є змінні для фонтів  // fonts
    --font-family-main: 'DM Sans',
        sans-serif;
    --font-family-title: 'Titan One',
        cursive;

2022-06-26 14:24 UTC, JuliaGolban commented on src/sass/layouts/_contacts.scss
> +    font-family: 'DM Sans';
--font-family-main: 'DM Sans', у нас на боди, то можно його просто наслідувати

2022-06-26 14:24 UTC, JuliaGolban commented on src/sass/layouts/_contacts.scss
> +    font-family: 'DM Sans';
аналогічно і з color: var(--cl-txt-main);
    background-color: var(--bgc-main);

2022-06-26 14:25 UTC, JuliaGolban commented on src/sass/layouts/_contacts.scss
> +    border: 1px solid #E1E1E1;
в нас є --cl-txt-light: #e1e1e1;

2022-06-26 14:25 UTC, JuliaGolban commented on src/sass/layouts/_contacts.scss
> +        border: 1px solid #E1E1E1;
--cl-txt-light: #e1e1e1;

2022-06-26 14:26 UTC, JuliaGolban commented on src/sass/layouts/_contacts.scss
> +    line-height: 186%;
пишіть через 1,86

2022-06-26 14:29 UTC, JuliaGolban requested changes
повиправляйте коментарі

2022-06-26 15:52 UTC, OlenaBut reviewed
наче, все виправила

2022-06-26 16:14 UTC, JuliaGolban requested changes
додати загальний клас section, переробити margin, видалити зайві div, виправити дату та час

2022-06-26 17:01 UTC, Hresko approved these changes

2022-06-26 17:06 UTC, JuliaGolban approved these changes
з послідуючою доробкою

2022-06-26 17:07 UTC, JuliaGolban approved these changes

2022-06-26 17:14 UTC, merged